version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      # first container with php/mysql
      - image: circleci/php:7.1-node-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: homestead
          MYSQL_USER: homestead
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: secret

      # secondary container for mysql
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/laravel # directory where steps will run

    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory

      - run: sudo apt-get update

      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

      # run composer update, ignoring dev requires
      - run: composer update --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

      # install mysql client on first container
      - run: sudo apt install -y mysql-client

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      #- run: composer install -n --prefer-dist
      - run: composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor