version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      # Ubuntu 14.14
      #- image: circleci/php:7.1-node-browsers

      # Latest CentOS image
      # image: centos/centos7

      - image: amazonlinux:2017.12
    working_directory: ~/laravel # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory

      - run: yum -y update
      - run: yum -y install php71
      - run: yum -y install iputils

      - run: sudo curl -sS https://getcomposer.org/installer | sudo php
      - run: sudo mv composer.phar /usr/local/bin/composer
      - run: sudo ln -s /usr/local/bin/composer /usr/bin/composer

      - run: sudo composer install

      #- run: sudo apt-get update
      #- run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor