version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker 
      #- image: circleci/php:latest # ...with this image as the primary container; this is where all `steps` will run
      - image: circleci/php:7.1-node-browsers

    working_directory: ~/laravel # directory where steps will run

    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory

      - run: sudo apt install -y mysql-client
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip

      - run: sudo composer self-update

      - restore_cache:
        keys:
          - composer-v1-{{ checksum "composer.json" }}
          - composer-v1-
        - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor