version: 2 # use CircleCI 2.0

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/laravel # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory

      # Update image os
      - run: sudo apt-get update

      # Add zlib references
      - run: sudo apt install -y zlib1g-dev

      # Add php extensions
      - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
